sudo: required
services:
- docker

before_install:
- docker build -t radomir/complex-test -f ./client/Dockerfile.dev ./client

script:
- docker run radomir/complex-test npm run test -- --coverage

after_success:
  - docker build -t raso354/complex-client ./client
  - docker build -t raso354/complex-nginx ./nginx
  - docker build -t raso354/complex-server ./server
  - docker build -t raso354/complex-worker ./worker
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push raso354/complex-client
  - docker push raso354/complex-nginx
  - docker push raso354/complex-server
  - docker push raso354/complex-worker